%RUN  HBPL end-to-end on NTU RGB+D (60 classes, cross-subject protocol).
%
%   Reproduces the NTU RGB+D column of Tables II and III in
%   Shao et al., "A Hierarchical Model for Human Action Recognition from
%   Body-Parts", IEEE TCSVT 29(10):2986-2998, 2019.
%
%   Prerequisites
%     1. hbplSetup('ntu_rgbd')       puts VLFeat, libsvm and this pipeline on the path
%     2. the NTU skeleton files       point HBPL_RAW_DIR at them, or drop them
%                                     under <repo>/data
%
%   Pipeline
%     getLabels                   -> cross-subject train/test split
%     GeneFeatsPerBody            -> HRRV descriptors  (RRV_DB, RRV_SAMPLES)
%     GeneFisherCodeJointPyramid  -> Fisher vectors    (traindata<k>, testdata<k>)
%     trainBinRegression_shuffleBatch -> HBPL weights  (theta)
%     predictBinRegression        -> labels, confusion matrix, accuracy
%
%   The hierarchy of body-parts defined below follows Table I: layer 1 has 5
%   coarse parts per subject, layer 2 has 10, layer 3 has 19. NTU clips may
%   contain two subjects, so every count is doubled -> partGroup = [10 20 38].
%
%   Runtime is dominated by the Fisher-vector stage and is measured in hours.
%
%   See also HBPLSETUP, HBPLDATADIR, TESTFORNOISE, TESTFOROCCLUSION.

clear all
%% define the experiment times and class numbers
EXPERIMENT_TIMES=1;
experiment_num = EXPERIMENT_TIMES;
CLASS_NUM = 60;% class numbers for classification task
%% location of the raw skeleton files (override with HBPL_RAW_DIR)
BAT_FOLDER = hbplDataDir('raw');
file_ext = '.skeleton';

distance_matrix_smml = cell(1,EXPERIMENT_TIMES);
confusion_matrix_smml = cell(1,EXPERIMENT_TIMES);
distance_matrix_diff = cell(1,EXPERIMENT_TIMES);
confusion_matrix_diff = cell(1,EXPERIMENT_TIMES);
compu_time_svm = zeros(1,EXPERIMENT_TIMES);
compu_time_diff = zeros(1,EXPERIMENT_TIMES);
compu_time_bof = zeros(1,EXPERIMENT_TIMES);
recog_ratio_diff = zeros(1,EXPERIMENT_TIMES);
recog_ratio_smml = zeros(1,EXPERIMENT_TIMES);
%% define the joint name of body 1
RANK_1 = '19' ;RKNE_1 = '18';LANK_1 = '15';LKNE_1 = '14';
LELB_1 = '6';LWRA_1 = '7';RELB_1 = '10';RWRA_1 = '11';
STRN_1 = '1';HEAD_1 = '4';RSHO_1 = '9';LSHO_1 = '5';
LFWT_1 = '13'; RFWT_1 = '17';C7_1 ='21';T10_1= '2';
RFIN_1 = '24';LFIN_1 = '22';RTOE_1 = '20';LTOE_1 = '16';
ENSEMBLE = 'ENSEMBLE';
%% define the joint name of body 2
RANK_2 = '44' ;RKNE_2 = '43';LANK_2 = '40';LKNE_2 = '39';
LELB_2 = '31';LWRA_2 = '32';RELB_2 = '35';RWRA_2 = '36';
STRN_2 = '26';HEAD_2 = '29';RSHO_2 = '34';LSHO_2 = '30';
LFWT_2 = '38'; RFWT_2 = '42';C7_2 ='46';T10_2= '27';
RFIN_2 = '49';LFIN_2 = '47';RTOE_2 = '45';LTOE_2 = '41';
ENSEMBLE = 'ENSEMBLE';
%% joints number in the skeleton of NTU-3D


% partition joints into 50 groups
joints_no = {HEAD_1;C7_1;RFIN_1;RWRA_1;RELB_1;RSHO_1;LFIN_1;LWRA_1;LELB_1;LSHO_1;
             T10_1;STRN_1;RFWT_1;RKNE_1;RANK_1;RTOE_1;LFWT_1;LKNE_1;LANK_1;LTOE_1;
             HEAD_2;C7_2;RFIN_2;RWRA_2;RELB_2;RSHO_2;LFIN_2;LWRA_2;LELB_2;LSHO_2;
             T10_2;STRN_2;RFWT_2;RKNE_2;RANK_2;RTOE_2;LFWT_2;LKNE_2;LANK_2;LTOE_2}; 
 
% joint groups for virture rigid bodies      
bodyJoints = { 
                       HEAD_1 STRN_1;...
                       C7_1   RFIN_1;...
                       C7_1   LFIN_1;...
                       STRN_1 RTOE_1;...
                       STRN_1 LTOE_1;...
                       HEAD_2 STRN_2;...
                       C7_2   RFIN_2;...
                       C7_2   LFIN_2;...
                       STRN_2 RTOE_2;...
                       STRN_2 LTOE_2;...
                       
                        HEAD_1 T10_1;...
                        C7_1   STRN_1;....
                        C7_1   RELB_1;...
                        RELB_1 RFIN_1;...
                        C7_1   LELB_1;...
                        LELB_1 LFIN_1;...
                        STRN_1 RKNE_1;...
                        RKNE_1 RTOE_1;...
                        STRN_1 LKNE_1;...
                        LKNE_1 LTOE_1;...
                        HEAD_2 T10_2;...
                        C7_2   STRN_2;....
                        C7_2   RELB_2;...
                        RELB_2 RFIN_2;...
                        C7_2   LELB_2;...
                        LELB_2 LFIN_2;...
                        STRN_2 RKNE_2;...
                        RKNE_2 RTOE_2;...
                        STRN_2 LKNE_2;...
                        LKNE_2 LTOE_2;...

                      
                      HEAD_1  C7_1;...
                      C7_1    RSHO_1;...
                      RSHO_1  RELB_1;...
                      RELB_1  RWRA_1;...
                      RWRA_1 RFIN_1;...
                      C7_1    LSHO_1;...
                      LSHO_1  LELB_1;...
                      LELB_1  LWRA_1;...
                      LWRA_1 LFIN_1;...
                      C7_1    T10_1;...
                      T10_1   STRN_1;...
                      STRN_1  RFWT_1;...
                      RFWT_1  RKNE_1;...
                      RKNE_1  RANK_1;...
                      RANK_1  RTOE_1;...
                      STRN_1  LFWT_1;...
                      LFWT_1  LKNE_1;...
                      LKNE_1  LANK_1;...
                      LANK_1  LTOE_1;...
                      HEAD_2  C7_2;...
                      C7_2    RSHO_2;...
                      RSHO_2  RELB_2;...
                      RELB_2  RWRA_2;...
                      RWRA_2 RFIN_2;...
                      C7_2    LSHO_2;...
                      LSHO_2  LELB_2;...
                      LELB_2  LWRA_2;...
                      LWRA_2 LFIN_2;...
                      C7_2    T10_2;...
                      T10_2   STRN_2;...
                      STRN_2  RFWT_2;...
                      RFWT_2  RKNE_2;...
                      RKNE_2  RANK_2;...
                      RANK_2  RTOE_2;...
                      STRN_2  LFWT_2;...
                      LFWT_2  LKNE_2;...
                      LKNE_2  LANK_2;...
                      LANK_2  LTOE_2;...
                      };
jointGroup = size(bodyJoints,1);
Normalize_Joints = {    
                    C7_1   STRN_1;...
                    RFWT_1 LFWT_1;...        
                   }; %Normalize the skeleton using these key joints nearby the STRN join

% fprintf ('copying original data...\n');
%  for i=1:length(joints_no)
%     copymat_file = joints_no{i};
%     copyfile(['CV_joints/' copymat_file '*.mat'],'../NTU3DActionEvaluatingCode/','f');
% end
[trainGID,testGID] = getLabels(joints_no);
GeneFeatsPerBody(bodyJoints,Normalize_Joints);% generate RRV_DB and RRV_SAMPLES
ntotalbh = 3; % l = 0,1,2,3 (L=3) blocks are 2^(l)
numClusters = 32;%128
batchsize = 256;
jointNum = jointGroup;
% temporal pyramid baded on pooling fisher codes
% [trainGID,testGID] = GeneFisherCodeJointPyramid_Pairdist(jointNum, ntotalbh, numClusters,trainGID,testGID,batchsize,1);%for pairdist descriptors
[trainGID,testGID] = GeneFisherCodeJointPyramid(jointNum, ntotalbh, numClusters,trainGID,testGID,batchsize,0);% encoding descriptors by fisher vectors
save trainGID trainGID;save testGID testGID;
load trainGID;load testGID;
jointNum = jointGroup; % for single modality
numTrain = length(trainGID);numTest = length(testGID);
%         lambda = [0.01,0.5,0];modalityNum = 1;
lambda = [0.001,0.2,0.0];modalityNum = 1;
theta = trainBinRegression_shuffleBatch(trainGID,lambda,jointNum,modalityNum,batchsize);
predict_label = predictBinRegression(theta,testGID,batchsize);
load modelForTest; modelForTest.theta = theta; save modelForTest modelForTest; clear modelForTest;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%1st type of svm linear classifer
% load traindata.mat;model =  svmtrain(trainGID,traindata', '-c 1 -g 0.07 -t 0 -b 1');clear traindata;
% load testdata.mat;[predict_label, accuracy, dec_values] = svmpredict(testGID,testdata', model,'-b 1');clear testdata;

%2nd type of svm linear classifer
% lambda = 0.1;     % regularization parameter for w
% load traindata.mat;[w, b, class_name] = li2nsvm_multiclass_lbfgs(traindata',trainGID, lambda);clear traindata;
% 
% tic;
% load testdata.mat;[predict_label, ~] = li2nsvm_multiclass_fwd(testdata', w, b, class_name);clear testdata;
% sum_time_svm = toc;
% compu_time_ssm(experiment_num) =sum_time_svm/length(predict_label);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

confusion_matrix = zeros(CLASS_NUM,CLASS_NUM);
for i = 1:CLASS_NUM
    for j = 1:CLASS_NUM
        confusion_matrix(i,j) = length(find(testGID == i & predict_label == j));
    end
end
recog_ratio_smml(experiment_num) = trace(confusion_matrix)/sum(confusion_matrix(:));
recog_ratio_final_smml = mean(recog_ratio_smml) %#ok<NOPTS>
confusion_matrix_smml{1,experiment_num} = confusion_matrix;
