CLASS_NUM = 60; % class numbers for classification task
RANK_1 = '19'; RKNE_1 = '18'; LANK_1 = '15'; LKNE_1 = '14';
LELB_1 = '6'; LWRA_1 = '7'; RELB_1 = '10'; RWRA_1 = '11';
STRN_1 = '1'; HEAD_1 = '4'; RSHO_1 = '9'; LSHO_1 = '5';
LFWT_1 = '13'; RFWT_1 = '17'; C7_1 = '21'; T10_1 = '2';
RFIN_1 = '24'; LFIN_1 = '22'; RTOE_1 = '20'; LTOE_1 = '16';
ENSEMBLE = 'ENSEMBLE';
%% define the joint name of body 2
RANK_2 = '44'; RKNE_2 = '43'; LANK_2 = '40'; LKNE_2 = '39';
LELB_2 = '31'; LWRA_2 = '32'; RELB_2 = '35'; RWRA_2 = '36';
STRN_2 = '26'; HEAD_2 = '29'; RSHO_2 = '34'; LSHO_2 = '30';
LFWT_2 = '38'; RFWT_2 = '42'; C7_2 = '46'; T10_2 = '27';
RFIN_2 = '49'; LFIN_2 = '47'; RTOE_2 = '45'; LTOE_2 = '41';
ENSEMBLE = 'ENSEMBLE';
%% joints number in the skeleton of NTU-3D
% partition joints into 50 groups
joints_no = {HEAD_1; C7_1; RFIN_1; RWRA_1; RELB_1; RSHO_1; LFIN_1; LWRA_1; LELB_1; LSHO_1
             T10_1; STRN_1; RFWT_1; RKNE_1; RANK_1; RTOE_1; LFWT_1; LKNE_1; LANK_1; LTOE_1
             HEAD_2; C7_2; RFIN_2; RWRA_2; RELB_2; RSHO_2; LFIN_2; LWRA_2; LELB_2; LSHO_2
             T10_2; STRN_2; RFWT_2; RKNE_2; RANK_2; RTOE_2; LFWT_2; LKNE_2; LANK_2; LTOE_2};

% joint groups for virtual rigid bodies
bodyJoints = {
              HEAD_1 STRN_1; ...
              C7_1   RFIN_1; ...
              C7_1   LFIN_1; ...
              STRN_1 RTOE_1; ...
              STRN_1 LTOE_1; ...
              HEAD_2 STRN_2; ...
              C7_2   RFIN_2; ...
              C7_2   LFIN_2; ...
              STRN_2 RTOE_2; ...
              STRN_2 LTOE_2
              HEAD_1 T10_1; ...
              C7_1   STRN_1; ....
              C7_1   RELB_1; ...
              RELB_1 RFIN_1; ...
              C7_1   LELB_1; ...
              LELB_1 LFIN_1; ...
              STRN_1 RKNE_1; ...
              RKNE_1 RTOE_1; ...
              STRN_1 LKNE_1; ...
              LKNE_1 LTOE_1; ...
              HEAD_2 T10_2; ...
              C7_2   STRN_2; ....
              C7_2   RELB_2; ...
              RELB_2 RFIN_2; ...
              C7_2   LELB_2; ...
              LELB_2 LFIN_2; ...
              STRN_2 RKNE_2; ...
              RKNE_2 RTOE_2; ...
              STRN_2 LKNE_2; ...
              LKNE_2 LTOE_2
              HEAD_1  C7_1; ...
              C7_1    RSHO_1; ...
              RSHO_1  RELB_1; ...
              RELB_1  RWRA_1; ...
              RWRA_1 RFIN_1; ...
              C7_1    LSHO_1; ...
              LSHO_1  LELB_1; ...
              LELB_1  LWRA_1; ...
              LWRA_1 LFIN_1; ...
              C7_1    T10_1; ...
              T10_1   STRN_1; ...
              STRN_1  RFWT_1; ...
              RFWT_1  RKNE_1; ...
              RKNE_1  RANK_1; ...
              RANK_1  RTOE_1; ...
              STRN_1  LFWT_1; ...
              LFWT_1  LKNE_1; ...
              LKNE_1  LANK_1; ...
              LANK_1  LTOE_1; ...
              HEAD_2  C7_2; ...
              C7_2    RSHO_2; ...
              RSHO_2  RELB_2; ...
              RELB_2  RWRA_2; ...
              RWRA_2 RFIN_2; ...
              C7_2    LSHO_2; ...
              LSHO_2  LELB_2; ...
              LELB_2  LWRA_2; ...
              LWRA_2 LFIN_2; ...
              C7_2    T10_2; ...
              T10_2   STRN_2; ...
              STRN_2  RFWT_2; ...
              RFWT_2  RKNE_2; ...
              RKNE_2  RANK_2; ...
              RANK_2  RTOE_2; ...
              STRN_2  LFWT_2; ...
              LFWT_2  LKNE_2; ...
              LKNE_2  LANK_2; ...
              LANK_2  LTOE_2 ...
             };
jointGroup = size(bodyJoints, 1);
Normalize_Joints = {
                    C7_1   STRN_1; ...
                    RFWT_1 LFWT_1 ...
                   }; % Normalize the skeleton using these key joints nearby the STRN join
% noise_level = [0.1 0.08 0.06 0.04 0.02 0.01 0];
noise_level = [0.005 0.01 0.015 0.02 0.025 0.03];
occlu_ratio = zeros (1, 6);
for m = 1:30
    for n = 1:6
        experiment_num = n;
        fprintf ('copying original data...\n');
        for i = 1:length(joints_no)
            copymat_file = joints_no{i};
            copyfile(['CV_joints/' copymat_file '*.mat'], '../NTU3DActionEvaluatingCode/', 'f');
        end
        %% add Guassian White Noise to Samples data
        add_noise_bat(joints_no, noise_level(experiment_num), occlu_ratio(experiment_num));
        [trainGID, testGID] = getLabels(joints_no);
        batchsize = 256;
        [RRV_SAMPLES]  = GeneFeatsPerBodyForTest(bodyJoints, Normalize_Joints);
        ntotalbh = 2; % l = 0,1,2,3 (L=3) blocks are 2^(l)
        jointNum = jointGroup;
        % temporal pyramid based on pooling fisher codes
        GeneFisherCodeJointPyramidForTest(RRV_SAMPLES, jointNum, ntotalbh, batchsize, 0);
        clear RRV_SAMPLES; % to avoid Out of Memory

        %% ------------------------------------------------------------------%%
        load modelForTest; theta = modelForTest.theta; clear modelForTest;
        predict_label = predictBinRegression(theta, testGID, batchsize);

        %% ----------------------------------------------------------------%%
        confusion_matrix = zeros(CLASS_NUM, CLASS_NUM);
        for i = 1:CLASS_NUM
            for j = 1:CLASS_NUM
                confusion_matrix(i, j) = length(find(testGID == i & predict_label == j));
            end
        end
        recog_ratio_smml(experiment_num) = trace(confusion_matrix) / sum(confusion_matrix(:));
        recog_ratio_final_smml = mean(recog_ratio_smml) %#ok<NOPTS>
        confusion_matrix_smml{1, experiment_num} = confusion_matrix;

        %% change every test
        %     save test_occlu8 recog_ratio_smml recog_ratio_final_smml confusion_matrix_smml
        eval(['save ' strcat('test_noise', num2str(m)) ' recog_ratio_smml recog_ratio_final_smml confusion_matrix_smml']);
    end
end

recog_ratio_noise = 0;
for i = 1:m
    eval(['load ' strcat('test_noise', num2str(i))]);
    recog_ratio_noise = recog_ratio_smml + recog_ratio_noise;
end
recog_ratio_noise = recog_ratio_noise / m;
plot(recog_ratio_noise, 'g');
